@port=3000

###
GET http://localhost:{{port}}

### 
GET http://localhost:{{port}}/about


###
POST http://localhost:3000/postsomething
Content-Type: application/json

{
  "name": "John Doe",
  "age": 30
}